package runner;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;
import report_utility.beans.*;
import report_utility.core.Report;
import report_utility.core.ReportBuilder;
import report_utility.enums.ComponentType;

public class AuditReport {
  public static void main(String[] args) {

    try {
      String outputPath = "/home/p3/IdeaProjects/Report_Utility/output";
      Report report = new ReportBuilder(outputPath, "Audit.pdf").build();
      report.addComponent(ComponentType.HEADER, HeaderBean.DEFAULT_CONFIG);
      Map<String, String> parameters = new LinkedHashMap<>();
      parameters.put("Generated By", "Sysadmin");
      parameters.put("View Activity Session Id", "1234567890");
      parameters.put("Report Generated Time", new Date().toString());

      Map<String, String> jobSummaryParameters = new LinkedHashMap<>();
      jobSummaryParameters.put("Scheduled By", "Sysadmin");
      jobSummaryParameters.put("Scheduled Time", new Date().toString());
      jobSummaryParameters.put("Start Time", new Date().toString());
      jobSummaryParameters.put("End Time", new Date().toString());
      jobSummaryParameters.put("Total Time", new Date().toString());

      report.addComponent(
          ComponentType.GRID_SECTION, GridTableBean.builder().gridValues(parameters).build());

      report.addComponent(ComponentType.FOOTER, FooterBean.DEFAULT_CONFIG);
      report.render();
      report.close();
    } catch (FileNotFoundException e) {
      throw new IllegalArgumentException(e.getMessage());
    } catch (IOException e) {
      throw new IllegalArgumentException(e);
    }
  }
}
