package runner.component;

import lombok.extern.slf4j.Slf4j;
import report_utility.beans.FooterBean;
import report_utility.beans.GridTableBean;
import report_utility.beans.HeaderBean;
import report_utility.beans.ObjectiveBean;
import report_utility.core.Report;
import report_utility.core.ReportBuilder;
import report_utility.enums.ComponentType;
import report_utility.enums.TableType;
import runner.enums.ReportNameConstants;
import runner.services.CommonRunner;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

@Slf4j
public class MaterializedViewRunner implements CommonRunner {
    @Override
    public void generateReport(String location, ReportNameConstants reportNameConstants) {
        try {
            Report report = new ReportBuilder(location, reportNameConstants.getFileName()).build();
            report.addComponent(ComponentType.HEADER, HeaderBean.DEFAULT_CONFIG);
            Map<String, String> parameters = new LinkedHashMap<>();
            parameters.put("Generated By", "Sysadmin");
            parameters.put("View Activity Session Id", "1234567890");
            parameters.put("Report Generated Time", new Date().toString());

            Map<String, String> jobSummaryParameters = new LinkedHashMap<>();
            jobSummaryParameters.put("Scheduled By", "Sysadmin");
            jobSummaryParameters.put("Scheduled Time", new Date().toString());
            jobSummaryParameters.put("Start Time", new Date().toString());
            jobSummaryParameters.put("End Time", new Date().toString());
            jobSummaryParameters.put("Total Time", new Date().toString());

            Map<String, String> additionalParameters = new LinkedHashMap<>();
            additionalParameters.put("Record Count Before Refresh", "0");
            additionalParameters.put("Record Count After Refresh", "702");

            report.addComponent(ComponentType.GRID_SECTION, GridTableBean.builder().gridValues(parameters).build());
            report.addComponent(ComponentType.GRID_SECTION, GridTableBean.builder().gridValues(jobSummaryParameters)
                    .title("Job Summary")
                    .tableType(TableType.SUMMARY)
                    .isJobStatusInclusion(true)
                    .build());
            String reportDescription = "This report contains details of the end-to-end data and metadata track of the data object from the point of extraction to "
                    + "ingestion into Archon Data Store. Chain of custody checks are run for each object, and their status is listed alongside. "
                    + "Go through them to ensure your data has been mapped without errors.";
            report.addComponent(ComponentType.OBJECTIVE, ObjectiveBean.builder().description(reportDescription).build());

            report.addComponent(ComponentType.GRID_SECTION, GridTableBean.builder()
                    .gridValues(additionalParameters)
                    .tableType(TableType.SUMMARY)
                    .title("Additional Details").build());

            report.addComponent(ComponentType.FOOTER, FooterBean.DEFAULT_CONFIG);
            report.render();
            report.close();
        } catch (FileNotFoundException e) {
            throw new IllegalArgumentException(e.getMessage());
        } catch (IOException e) {
            throw new IllegalArgumentException(e);
        }

    }
}
