package com.p3.ads.runner.utils;

import lombok.experimental.UtilityClass;
import runner.enums.ReportNameConstants;

import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

@UtilityClass
public class DataBuilderUtils {

  public static Map<String, String> buildHeaderParameters(ReportNameConstants reportNameConstants) {
    Map<String, String> parameters = new LinkedHashMap<>();
    parameters.put("Generated By", "Daniel Kumar");
    switch (reportNameConstants) {
      case MATERIALIZED_VIEW_REFRESH_REPORT:
        parameters.put("View Activity Session Id", "1234567891234");
        parameters.put("Report Generated Time", new Date().toString());
        return parameters;
      case ROLLBACK_REPORT:
        parameters.put("Rollback Id", "1234567890");
        parameters.put("Report Generated Time", new Date().toString());
        return parameters;
      case TABLE_OPTIMIZATION_REPORT:
      case SOURCE_TO_TARGET_VALIDATION_REPORT:
      case LICENSE_VOLUME_STATISTICS_REPORT:
      case CONSOLIDATED_INGESTION_VALIDATION_REPORT:
      case INGESTION_REPORT:
        parameters.put("Job Name", "Job Name");
        parameters.put("Report Generated Time", new Date().toString());
        return parameters;
      case CHAIN_OF_CUSTODY_REPORT:
        parameters.put("Job Id", "1234567890");
        parameters.put("Report Generated Time", new Date().toString());
        return parameters;
      case AUDIT_REPORT:
      case PURGE_REPORT:
        parameters.put("Report Generated Time", new Date().toString());
        return parameters;
      default:
        throw new IllegalArgumentException("Unsupported report type " + reportNameConstants);
    }
  }

  public static Map<String, String> buildJobSummaryParameters(ReportNameConstants type) {
    Date scheduledTime = new Date();
    Map<String, String> contentMap = new LinkedHashMap<>();
    Date startTime = new Date();

    switch (Objects.requireNonNull(type)) {
      case MATERIALIZED_VIEW_REFRESH_REPORT:
        contentMap.put("Job Type", "Materialized View Refresh Report");
        addCommonContent(contentMap, startTime, scheduledTime);
        contentMap.put("Schema Name", "Schema Name");
        contentMap.put("Materialized View Name", "JOINVIEW");
        break;
      case TABLE_OPTIMIZATION_REPORT:
        contentMap.put("Job Instance Id", "0123546474-5252");
        contentMap.put("Job Type", "Table Data Optimization");
        addCommonContent(contentMap, startTime, scheduledTime);
        contentMap.put("Schema Name", "Schema Name");
        contentMap.put("Table Name", "Address Table");
        break;
      case INGESTION_REPORT:
        addCommonContent(contentMap, startTime, scheduledTime);
        contentMap.put("Schema Name", "Schema Name");
        addCommonContentForIngestionAndSourceValidation(contentMap);
        break;
      case LICENSE_VOLUME_STATISTICS_REPORT:
        contentMap.put("Job Name", "Job_Name_123456");
        contentMap.put("Scheduled By", "Sysadmin");
        contentMap.put("Scheduled Time", scheduledTime.toString());
        contentMap.put("Start Time", startTime.toString());
        contentMap.put("End Time", new Date().toString());
        contentMap.put("Total Time", totalTimeCalculation(startTime, new Date()));
        break;
      case SOURCE_TO_TARGET_VALIDATION_REPORT:
        contentMap.put("Ingestion Session Id", "1234567890123");
        addCommonContent(contentMap, startTime, scheduledTime);
        contentMap.put("Schema Name", "Schema Name");
        addCommonContentForIngestionAndSourceValidation(contentMap);
        break;
      case PURGE_REPORT:
        contentMap.put("Purge list name", "PURGE_LIST - (1713852484696)");
        contentMap.put("Retention policy", "EB -15");
        contentMap.put("Purge level", "Record/Group");
        contentMap.put("Time of purge", new Date().toString());
        break;
      case ROLLBACK_REPORT:
        addCommonContent(contentMap, startTime, scheduledTime);
        contentMap.put("Ingestion Session Id", "1234567890123");
        contentMap.put("Ingestion type", "Rest");
        contentMap.put("Rollback Reason", "Data duplicated");
        contentMap.put("Rollback Notes", "notes for rollback");
        break;
      case CONSOLIDATED_INGESTION_VALIDATION_REPORT:
        contentMap.put("Job Session Id", "1ef9b1d5-7533-4689-83fc");
        contentMap.put("Job Type", "Consolidated Ingestion Report");
        addCommonContent(contentMap, startTime, scheduledTime);
        contentMap.put("Schema Regex", "N/A");
        contentMap.put("Table Regex", "N/A");
        contentMap.put("Number of schemas involved", "1");
        contentMap.put("Number of tables involved", "1");
        contentMap.put("Number of ingestion sessions involved", "1");
        break;
      case CHAIN_OF_CUSTODY_REPORT:
        contentMap.put("Job Type", "Sysadmin");
        addCommonContent(contentMap, startTime, scheduledTime);
        break;
      default:
        throw new IllegalArgumentException("Unsupported content type: " + type);
    }
    return contentMap;
  }

  private static void addCommonContentForIngestionAndSourceValidation(
      Map<String, String> contentMap) {
    contentMap.put("Table Name", "Claim");
    contentMap.put("Ingestion Type", "REST");
    contentMap.put("Ingestion Mode", "Ingest Data");
    contentMap.put("Source Data Storage Profile ", "Local File System");
    contentMap.put("Storage Type", "Default Storage");
    contentMap.put("Bucket Name", "N/A");
    contentMap.put("Bucket Type", "N/A");
    contentMap.put("Region", "N/A");
    contentMap.put("Source path", "src/main/resources");
    contentMap.put("Files Count Per Set", "10");
  }

  private static void addCommonContent(
      Map<String, String> contentMap, Date startTime, Date scheduledTime) {
    contentMap.put("Scheduled By", "Sysadmin");
    contentMap.put("Scheduled Time", scheduledTime.toString());
    contentMap.put("Start Time", new Date().toString());
    contentMap.put("End Time", new Date().toString());
    contentMap.put("Total Time", totalTimeCalculation(startTime, new Date()));
    contentMap.put("Application Name", "App name");
  }

  private static String totalTimeCalculation(Date startTime, Date endTime) {
    long difference = startTime.getTime() - endTime.getTime();
    return Long.toString((difference / 1000) % 60);
  }

  public static String buildObjectiveDescription(ReportNameConstants type) {
    switch (Objects.requireNonNull(type)) {
      case MATERIALIZED_VIEW_REFRESH_REPORT:
        return "This report gives details on materialized view updates.The materialized view"
            + "after being created once,needs to refreshed at intervals to get real time"
            + "data.Find the details of this job run below";
      case TABLE_OPTIMIZATION_REPORT:
        return "This report shows the storage optimisation achieved after the process run. "
            + "Table data optimisation jobs identify scope of optimising the way this data is stored "
            + "using all the data and metadata information available for that table. "
            + "This involves techniques like merging data sets, compressing data, cleaning up fragmented storage, etc.";
      case PURGE_REPORT:
        return "The purge report use case involves identifying and removing outdated or irrelevant data from the system to maintain and database "
            + "efficiency and integrity. It includes setting criteria for data to be purged, executing the purge process,and then verifying successful "
            + "deletion. This ensures optimized performance and compliance with data retention policies.";
      case ROLLBACK_REPORT:
        return "The rollback report use case focuses on documenting instances where system changes were reversed to a previous state. "
            + "It includes capturing details of the rollback event, such as the reason for the rollback, the changes that were undone, and the "
            + "impact on the system. This report helps in analyzing the stability of updates and provides insights for preventing future issues.";
      case SOURCE_TO_TARGET_VALIDATION_REPORT:
        return "The Source to Target Validation Report ensures data integrity and accuracy during data migration or ETL (Extract, Transform"
            + "Load) processes. It includes checks to confirm that data from the source matches the data loaded into the target system"
            + "verifying record counts, data types, and key business rules. This report helps identify discrepancies early, ensuring reliable"
            + "and consistent data transfer, which is critical for maintaining data quality in the target system.";
      case LICENSE_VOLUME_STATISTICS_REPORT:
        return "The License Volume Statistics Report provides detailed insights into the utilization of software licenses within an organization. "
            + "It includes metrics on the total number of licenses available, the number of licenses currently in use, and any remaining or unused licenses. "
            + "This report helps organizations manage compliance, optimize license allocation, and plan for future licensing needs, ensuring cost-effective use of software resources and adherence to licensing agreements.";
      case INGESTION_REPORT:
        return "The ingestion report details the process of importing data from various sources into the system. It includes metrics on data "
            + "volume, ingestion times, and success rates, as well as any errors or issues encountered. This report ensures that the data "
            + "ingestion process is efficient, accurate, and aligned with organizational requirements, providing a foundation for reliable data "
            + "analytics and operations.";
      case CONSOLIDATED_INGESTION_VALIDATION_REPORT:
        return "The Consolidated Ingestion Validation Report ensures the accuracy and completeness of data ingested into the system from "
            + "various sources. It includes validation checks for data integrity, consistency, and alignment with predefined standards. This "
            + "report helps identify and rectify discrepancies early, ensuring reliable data availability for downstream processes and analytics.";
      case CHAIN_OF_CUSTODY_REPORT:
        return "This report contains details of the end-to-end data and metadata track of the data object from the point of extraction to "
            + "ingestion into Archon Data Store. Chain of custody checks are run for each object, and their status is listed alongside. "
            + "Go through them to ensure your data has been mapped without errors.";
      default:
        throw new IllegalArgumentException("Unsupported report type " + type);
    }
  }
}
