package com.p3.ads.runner;

import com.p3.ads.beans.FooterBean;
import com.p3.ads.beans.GridTableBean;
import com.p3.ads.beans.HeaderBean;
import com.p3.ads.beans.SingleCardBean;
import com.p3.ads.core.Report;
import com.p3.ads.core.ReportBuilder;
import com.p3.ads.enums.ComponentType;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

public class AuditReport {
  public static void main(String[] args) {

    try {
      String outputPath = "/home/abirami/IdeaProjects/Report_Utility/output";
      Report report = new ReportBuilder(outputPath, "Audit.pdf").build();
      report.addComponent(ComponentType.HEADER, HeaderBean.DEFAULT_CONFIG);
      Map<String, String> parameters = new LinkedHashMap<>();
      parameters.put("Generated By", "Sysadmin");
      parameters.put("Job Name", "Audit Job");
      parameters.put("Report Generated Time", new Date().toString());

      report.addComponent(
          ComponentType.GRID_SECTION, GridTableBean.builder().gridValues(parameters).build());

      String firstHeaderValue =
          "User sysadmin (sysadmin@ads.com) exported the audit events for date range 2023-11-07 - 2024-06-12 as CSV";
      String firstHeader = " System | Management | Audit | Export";

      String secondHeaderValue =
          "Output of Searches job (Job_name_1717412150060) processed for search "
              + "'PartSupp_Supplier_Lineitem_Search_CustomTemp' under application "
              + "'TST_CUSTOMTEMP_TPCH_DATASET' was downloaded by user sysadmin (sysadmin@ads.com).";

      String secondHeader = "System | Processing | Background Jobs | Download";

      report.addComponent(
          ComponentType.CARD_SECTION,
          SingleCardBean.builder().header(firstHeader).value(firstHeaderValue).build());

      report.addComponent(
          ComponentType.CARD_SECTION,
          SingleCardBean.builder().header(secondHeader).value(secondHeaderValue).build());

      report.addComponent(
          ComponentType.CARD_SECTION,
          SingleCardBean.builder().header(firstHeader).value(firstHeaderValue).build());

      report.addComponent(
          ComponentType.CARD_SECTION,
          SingleCardBean.builder().header(secondHeader).value(secondHeaderValue).build());

      report.addComponent(ComponentType.FOOTER, FooterBean.DEFAULT_CONFIG);
      report.render();
      report.close();
    } catch (FileNotFoundException e) {
      throw new IllegalArgumentException(e.getMessage());
    } catch (IOException e) {
      throw new IllegalArgumentException(e);
    }
  }
}
