package com.p3.ads.runner;

import com.p3.ads.core.Report;
import com.p3.ads.core.ReportBuilder;
import com.p3.ads.enums.ComponentType;
import com.p3.ads.enums.FontFamilyType;
import com.p3.ads.enums.ProductLogo;
import com.p3.ads.enums.TableType;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class BillingTierUsageReportRunner {
    public static void main(String[] args) {
        try {
            String outputPath = "/home/abirami/IdeaProjects/Report_Utility/output";
            Report report = new ReportBuilder(outputPath, "BillingTierUsageReport.pdf").build();
            report.addComponent(ComponentType.HEADER,   HeaderBean.builder().title("Tier Plan Summary Report")
                    .fontColor("#030303")
                    .fontSize(SIXTEEN_FONT_SIZE)
                    .fontFamily(FontFamilyType.ROBOTO_MEDIUM)
                    .productLogo(ProductLogo.ARCHON_DATA_STORE)
                    .build());
            Map<String, String> parameters = new LinkedHashMap<>();
            parameters.put("Generated By", "Sysadmin");
            parameters.put("Generated on", LocalDate.now().toString());
            parameters.put("Information as on", LocalDate.now().toString());
            parameters.put("BillingCycle", "01/03/2023 - 30/03/2023");

            report.addComponent(
                    ComponentType.GRID_SECTION, GridTableBean.builder()
                            .title("")
                            .columnWidths(new float[]{300L, 300L, 300L, 300L})
                            .titleFontSize(EIGHT_FONT_SIZE)
                            .titleFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                            .titleFontColor(GRAY_FONT_COLOR)
                            .gridValues(new LinkedHashMap<>()) // Empty default map
                            .fontFamilyType(FontFamilyType.ROBOTO_MEDIUM) // Default font
                            .valueFontSize(TEN_FONT_SIZE) // Default font size
                            .headerFontSize(EIGHT_FONT_SIZE) // Default font size
                            .fontColor(BLACK_FONT_COLOR) // Default black color
                            .isJobStatusInclusion(false) // Default jobStatus Table as false
                            .tableType(TableType.HEADER) // Table Type -> Header
                            .jobStatusInputBean(JobStatusInputBean.DEFAULT_CONFIG)// Default job status config
                            .gridValues(parameters)
                            .isEmptySpaceNeededAtFront(false)
                            .build());


            Map<String, String> dataTierCardValues = new LinkedHashMap<>();
            dataTierCardValues.put("Current data tier","Tier 2");
            dataTierCardValues.put("Details", "Assigned as base tier for this billing period on 01/03/2024");

            MultipleCardBean dataTierCard =
                    MultipleCardBean.builder()
                            .title("Tier information")
                            .headerValue("DataTier")
                            .subHeaderValue("")
                            .values(dataTierCardValues)
                            .valueRowCount(2)
                            .isTitleDividerNeeded(false)
                            .isBottomDividerNeeded(false)
                            .borderRadius(3f)
                            .build();
            report.addComponent(ComponentType.CARD_SECTION, dataTierCard);


            Map<String, String> usageCardValues = new LinkedHashMap<>();
            usageCardValues.put("Current usage tier","Tier 3");
            usageCardValues.put("Details", "Upgraded due to high consumption of query units on 06/03/2024");

            MultipleCardBean usageTierCard =
                    MultipleCardBean.builder()
                            .headerValue("Usage Tier")
                            .subHeaderValue("")
                            .values(usageCardValues)
                            .valueRowCount(2)
                            .isTitleDividerNeeded(false)
                            .isBottomDividerNeeded(true)
                            .borderRadius(3f)
                            .build();
            report.addComponent(ComponentType.CARD_SECTION, usageTierCard);

            TableBean tableBean = TableBean.builder()
                    .title("Consumption information")
                    .headers(List.of("Parameter","AllocatedConsumed","(units & %)"))
                    .values(List.of(
                            List.of("Data","10 TB","8 TB (80%)"),
                            List.of("Query units","10000000","9000000 (90%)"),
                            List.of("Storage requests","5000000","4200000 (84%)"),
                            List.of("Data transfer","30 TB","24 TB (80%)"),
                            List.of("Users","100","80 (80%)"),
                            List.of("Concurrent users","100","6 (60%)"),
                            List.of("Compute","900 HRS","750 HRS (83.3%)"),
                            List.of("Backup management","20 TB","17 TB (85%)")
                    ))
                    .hasPercentageColorHighlight(true)
                    .percentageColorHighlight(RED_FONT_COLOR)
                    .headerFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                    .cellFontFamily(FontFamilyType.ROBOTO_REGULAR)
                    .headerFontSize(TEN_FONT_SIZE)
                    .cellFontSize(TEN_FONT_SIZE)
                    .borderRadius(3f)
                    .emptyLineNeedAtFront("false")
                    .drawDividerNeed("false")
                    .drawDividerNeedAtBottom("false")
                    .build();
            report.addComponent(ComponentType.TABLE, tableBean);
            report.addComponent(ComponentType.FOOTER, FooterBean.DEFAULT_CONFIG);
            report.render();
            report.close();
        } catch (FileNotFoundException e) {
            throw new IllegalArgumentException(e.getMessage());
        } catch (IOException e) {
            throw new IllegalArgumentException(e);
        }
    }
}
