package com.p3.ads.runner;

import com.p3.ads.core.Report;
import com.p3.ads.core.ReportBuilder;
import com.p3.ads.enums.ComponentType;
import com.p3.ads.enums.FontFamilyType;
import com.p3.ads.enums.ProductLogo;
import com.p3.ads.enums.TableType;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class BillingDashBoardReportRunner {
    public static void main(String[] args) {
        try {
            String outputPath = "/home/abirami/IdeaProjects/Report_Utility/output";
            Report report = new ReportBuilder(outputPath, "BillingDashBoardReport.pdf").build();
            report.addComponent(ComponentType.HEADER,   HeaderBean.builder().title("Billing Dashboard Report")
                    .fontColor("#030303")
                    .fontSize(SIXTEEN_FONT_SIZE)
                    .fontFamily(FontFamilyType.ROBOTO_MEDIUM)
                    .productLogo(ProductLogo.ARCHON_DATA_STORE)
                    .build());
            Map<String, String> parameters = new LinkedHashMap<>();
            parameters.put("Generated By", "Sysadmin");
            parameters.put("Generated on", LocalDate.now().toString());
            parameters.put("Information as on", LocalDate.now().toString());

            report.addComponent(
                    ComponentType.GRID_SECTION, GridTableBean.builder()
                            .title("")
                            .columnWidths(new float[]{300L, 300L, 300L})
                            .titleFontSize(EIGHT_FONT_SIZE)
                            .titleFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                            .titleFontColor(GRAY_FONT_COLOR)
                            .gridValues(new LinkedHashMap<>()) // Empty default map
                            .fontFamilyType(FontFamilyType.ROBOTO_MEDIUM) // Default font
                            .valueFontSize(TEN_FONT_SIZE) // Default font size
                            .headerFontSize(EIGHT_FONT_SIZE) // Default font size
                            .fontColor(BLACK_FONT_COLOR) // Default black color
                            .isJobStatusInclusion(false) // Default jobStatus Table as false
                            .tableType(TableType.HEADER) // Table Type -> Header
                            .jobStatusInputBean(JobStatusInputBean.DEFAULT_CONFIG)// Default job status config
                            .gridValues(parameters)
                            .isEmptySpaceNeededAtFront(false)
                            .build());



            Map<String, String> parameters1 = new LinkedHashMap<>();
            parameters1.put("Consumption Details", "During the billing period from 01/03/2023 to 30/03/2023");

            report.addComponent(
                    ComponentType.GRID_SECTION, GridTableBean.builder()
                            .title("")
                            .columnWidths(new float[]{1000L})
                            .titleFontSize(FOURTEEN_FONT_SIZE)
                            .titleFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                            .titleFontColor(GRAY_FONT_COLOR)
                            .gridValues(new LinkedHashMap<>()) // Empty default map
                            .fontFamilyType(FontFamilyType.ROBOTO_MEDIUM) // Default font
                            .valueFontSize(NINE_FONT_SIZE) // Default font size
                            .headerFontSize(FOURTEEN_FONT_SIZE) // Default font size
                            .fontColor(BLACK_FONT_COLOR) // Default black color
                            .isJobStatusInclusion(false) // Default jobStatus Table as false
                            .tableType(TableType.SUMMARY) // Table Type -> Header
                            .jobStatusInputBean(JobStatusInputBean.DEFAULT_CONFIG) // Default job status config
                            .gridValues(parameters1)
                            .build());

            List<CardValueBean> cardValueBeanList = new java.util.ArrayList<>();
            cardValueBeanList.add(
                    CardValueBean.builder()
                            .header("Data Tier Limit")
                            .body("4.5 TB")
                            .subBody("Consumed Out of 5 TB")
                            .footer("Current Tier: 1")
                            .build()
            );
            cardValueBeanList.add(CardValueBean.builder().build());
            cardValueBeanList.add(
                    CardValueBean.builder()
                            .header("Query Units")
                            .body("1,00,000")
                            .subBody("Consumed Out of 5,00,000")
                            .footer("Current Tier: 1")
                            .build()
            );
            cardValueBeanList.add(CardValueBean.builder().build());

            cardValueBeanList.add(
                    CardValueBean.builder()
                            .header("Data Transfer")
                            .body("4.5 TB")
                            .subBody("Consumed Out of 5 TB")
                            .footer("Current Tier: 1")
                            .build()
            );
            cardValueBeanList.add(CardValueBean.builder().build());

            cardValueBeanList.add(
                    CardValueBean.builder()
                            .header("Storage Requests")
                            .body("50,000")
                            .subBody("Consumed Out of 5,00,000")
                            .footer("Current Tier: 1")
                            .build()
            );
            cardValueBeanList.add(CardValueBean.builder().build());

            cardValueBeanList.add(
                    CardValueBean.builder()
                            .header("Total Users")
                            .body("100")
                            .subBody("Consumed Out of 500")
                            .footer("Current Tier: 1")
                            .build()
            );
            report.addComponent(ComponentType.CARD_LAYOUT, CardLayoutBean.builder()
                    .columnWidths(new float[]{300L, 30L , 300L, 30L , 300L, 30L , 300L, 30L,  300L})
                    .vauleList(cardValueBeanList)
                    .build());



            Map<String, String> dataTierParameter = new LinkedHashMap<>();
            dataTierParameter.put("Data Tier Consumption", "Generated on a daily basis from 01/03/2023 to 30/03/2023");

            report.addComponent(
                    ComponentType.TABLE_CONTAINER, TableContainerBean.builder()
                                    .gridTable(
                                    GridTableBean.builder()
                                    .title("")
                                    .columnWidths(new float[]{1000L})
                                    .titleFontSize(THIRTEEN_FONT_SIZE)
                                    .titleFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                                    .titleFontColor(GRAY_FONT_COLOR)
                                    .gridValues(new LinkedHashMap<>()) // Empty default map
                                    .fontFamilyType(FontFamilyType.ROBOTO_MEDIUM) // Default font
                                    .valueFontSize(NINE_FONT_SIZE) // Default font size
                                    .headerFontSize(FOURTEEN_FONT_SIZE) // Default font size
                                    .fontColor(BLACK_FONT_COLOR) // Default black color
                                    .isJobStatusInclusion(false) // Default jobStatus Table as false
                                    .tableType(TableType.SUMMARY) // Table Type -> Header
                                    .jobStatusInputBean(JobStatusInputBean.DEFAULT_CONFIG) // Default job status config
                                    .isEmptySpaceNeededAtFront(true)
                                    .gridValues(dataTierParameter)
                                    .build())
                            .table(
                                    TableBean.builder()
                                     .headers(List.of("Tier Name","Date","Allocated Size","Used Size"))
                                     .values(List.of(
                                        List.of("Tier 1","01/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","02/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","03/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","03/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","03/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","03/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","03/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","03/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","03/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","03/03/2023","25 TB","15 TB"),
                                        List.of("Tier 1","03/03/2023","25 TB","15 TB")
                    ))
                    .headerFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                    .cellFontFamily(FontFamilyType.ROBOTO_REGULAR)
                    .headerFontSize(TEN_FONT_SIZE)
                    .cellFontSize(TEN_FONT_SIZE)
                    .borderRadius(3f)
                    .emptyLineNeedAtFront("false")
                    .drawDividerNeed("false")
                    .drawDividerNeedAtBottom("true")
                    .build()).build());



            Map<String, String> queryUnitParameter = new LinkedHashMap<>();
            queryUnitParameter.put("Query Consumption", "Generated on a daily basis from 01/03/2023 to 30/03/2023");

            report.addComponent(
                    ComponentType.TABLE_CONTAINER,
                        TableContainerBean.builder().gridTable(GridTableBean.builder()
                            .title("")
                            .columnWidths(new float[]{1000L})
                            .titleFontSize(THIRTEEN_FONT_SIZE)
                            .titleFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                            .titleFontColor(GRAY_FONT_COLOR)
                            .gridValues(new LinkedHashMap<>()) // Empty default map
                            .fontFamilyType(FontFamilyType.ROBOTO_MEDIUM) // Default font
                            .valueFontSize(NINE_FONT_SIZE) // Default font size
                            .headerFontSize(FOURTEEN_FONT_SIZE) // Default font size
                            .fontColor(BLACK_FONT_COLOR) // Default black color
                            .isJobStatusInclusion(false) // Default jobStatus Table as false
                            .tableType(TableType.SUMMARY) // Table Type -> Header
                            .jobStatusInputBean(JobStatusInputBean.DEFAULT_CONFIG) // Default job status config
                            .gridValues(queryUnitParameter)
                            .isEmptySpaceNeededAtFront(false)
                            .startAtNewPage(true)
                            .build()).table(TableBean.builder()
                    .headers(List.of("Tier Name","Date","Allocated Units","Consumed Units"))
                    .values(List.of(
                            List.of("Tier 1","01/03/2023","10000","8000"),
                            List.of("Tier 1","01/03/2023","10000","8000"),
                            List.of("Tier 1","01/03/2023","10000","8000"),
                            List.of("Tier 1","01/03/2023","10000","8000")
                    ))
                    .headerFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                    .cellFontFamily(FontFamilyType.ROBOTO_REGULAR)
                    .headerFontSize(TEN_FONT_SIZE)
                    .cellFontSize(TEN_FONT_SIZE)
                    .borderRadius(3f)
                    .emptyLineNeedAtFront("false")
                    .drawDividerNeed("false")
                    .drawDividerNeedAtBottom("true").build()).build());


            Map<String, String> dataTransferParameter = new LinkedHashMap<>();
            dataTransferParameter.put("Data Transfer", "Generated on a daily basis from 01/03/2023 to 30/03/2023");

            report.addComponent(
                    ComponentType.TABLE_CONTAINER,
                    TableContainerBean.builder().gridTable( GridTableBean.builder()
                            .title("")
                            .columnWidths(new float[]{1000L})
                            .titleFontSize(THIRTEEN_FONT_SIZE)
                            .titleFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                            .titleFontColor(GRAY_FONT_COLOR)
                            .gridValues(new LinkedHashMap<>()) // Empty default map
                            .fontFamilyType(FontFamilyType.ROBOTO_MEDIUM) // Default font
                            .valueFontSize(NINE_FONT_SIZE) // Default font size
                            .headerFontSize(FOURTEEN_FONT_SIZE) // Default font size
                            .fontColor(BLACK_FONT_COLOR) // Default black color
                            .isJobStatusInclusion(false) // Default jobStatus Table as false
                            .tableType(TableType.SUMMARY) // Table Type -> Header
                            .jobStatusInputBean(JobStatusInputBean.DEFAULT_CONFIG) // Default job status config
                            .gridValues(dataTransferParameter)
                            .isEmptySpaceNeededAtFront(false)
                            .startAtNewPage(true)
                            .build())
                            .table( TableBean.builder()
                    .headers(List.of("Tier Name","Date","Allocated Size","Used Size"))
                    .values(List.of(
                            List.of("Tier 1","01/03/2023","25 TB","15 TB"),
                            List.of("Tier 1","02/03/2023","25 TB","15 TB")))
                    .headerFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                    .cellFontFamily(FontFamilyType.ROBOTO_REGULAR)
                    .headerFontSize(TEN_FONT_SIZE)
                    .cellFontSize(TEN_FONT_SIZE)
                    .borderRadius(3f)
                    .emptyLineNeedAtFront("false")
                    .drawDividerNeed("false")
                    .drawDividerNeedAtBottom("true")
                    .build()).build());


            Map<String, String> storageRequestParameter = new LinkedHashMap<>();
            storageRequestParameter.put("Storage Requests", "Generated on a daily basis from 01/03/2023 to 30/03/2023");

            report.addComponent(
                    ComponentType.TABLE_CONTAINER, TableContainerBean.builder().gridTable(GridTableBean.builder()
                            .title("")
                            .columnWidths(new float[]{1000L})
                            .titleFontSize(THIRTEEN_FONT_SIZE)
                            .titleFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                            .titleFontColor(GRAY_FONT_COLOR)
                            .gridValues(new LinkedHashMap<>()) // Empty default map
                            .fontFamilyType(FontFamilyType.ROBOTO_MEDIUM) // Default font
                            .valueFontSize(NINE_FONT_SIZE) // Default font size
                            .headerFontSize(FOURTEEN_FONT_SIZE) // Default font size
                            .fontColor(BLACK_FONT_COLOR) // Default black color
                            .isJobStatusInclusion(false) // Default jobStatus Table as false
                            .tableType(TableType.SUMMARY) // Table Type -> Header
                            .jobStatusInputBean(JobStatusInputBean.DEFAULT_CONFIG) // Default job status config
                            .gridValues(storageRequestParameter)
                            .startAtNewPage(true)
                            .isEmptySpaceNeededAtFront(false)
                            .build())
                            .table(TableBean.builder()
                    .headers(List.of("Tier Name","Date","Allocated Units","Consumed Units"))
                    .values(List.of(
                            List.of("Tier 1","01/03/2023","10000","8000"),
                            List.of("Tier 1","01/03/2023","10000","8000")
                    ))
                    .headerFontFamily(FontFamilyType.ROBOTO_MEDIUM)
                    .cellFontFamily(FontFamilyType.ROBOTO_REGULAR)
                    .headerFontSize(TEN_FONT_SIZE)
                    .cellFontSize(TEN_FONT_SIZE)
                    .borderRadius(3f)
                    .emptyLineNeedAtFront("false")
                    .drawDividerNeed("false")
                    .drawDividerNeedAtBottom("false")
                    .build()).build());

            report.addComponent(ComponentType.FOOTER, FooterBean.DEFAULT_CONFIG);
            report.render();
            report.close();
        } catch (FileNotFoundException e) {
            throw new IllegalArgumentException(e.getMessage());
        } catch (IOException e) {
            throw new IllegalArgumentException(e);
        }
    }
}
