package com.p3.ads.runner;

import com.p3.ads.core.Report;
import com.p3.ads.core.ReportBuilder;
import com.p3.ads.enums.ComponentType;
import com.p3.ads.enums.TableType;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

import static runner.constants.CommonConstants.JOB_SUMMARY;

public class ConsolidatedIngestionValidationReport {
  public static void main(String[] args) {
    try {
      String outputPath = "/home/abirami/IdeaProjects/Report_Utility/output";
      Report report = new ReportBuilder(outputPath, "Consolidated_Ingestion.pdf").build();
      report.addComponent(ComponentType.HEADER, HeaderBean.DEFAULT_CONFIG);
      Map<String, String> parameters = new LinkedHashMap<>();
      parameters.put("Generated By", "Sysadmin");
      parameters.put("Job Name", "123264656865");
      parameters.put("Report Generated Time", new Date().toString());

      report.addComponent(
          ComponentType.GRID_SECTION, GridTableBean.builder().gridValues(parameters).build());

      Map<String, String> jobSummaryParameters = new LinkedHashMap<>();
      jobSummaryParameters.put("Job Session Id", "1ef9b1d5-7533-4689-83fc-b");
      jobSummaryParameters.put("Job Type", "Consolidated Ingestion Report");
      jobSummaryParameters.put("Scheduled By", "Sysadmin");
      jobSummaryParameters.put("Scheduled Time", new Date().toString());
      jobSummaryParameters.put("Start Time", new Date().toString());
      jobSummaryParameters.put("End Time", new Date().toString());
      jobSummaryParameters.put("Total Time", new Date().toString());
      jobSummaryParameters.put("Application Name", "App name");
      jobSummaryParameters.put("Schema Regex", "N/A");
      jobSummaryParameters.put("Table Regex", "N/A");
      jobSummaryParameters.put("Number of schemas involved", "1");
      jobSummaryParameters.put("Number of tables involved", "1");
      jobSummaryParameters.put("Number of ingestion sessions involved", "1");

      report.addComponent(
          ComponentType.GRID_SECTION,
          GridTableBean.builder()
              .gridValues(jobSummaryParameters)
              .title(JOB_SUMMARY)
              .tableType(TableType.SUMMARY)
              .isJobStatusInclusion(true)
              .build());

      String reportDescription =
          "This report contains details of the end-to-end data and metadata track of the data object from the point of extraction to "
              + "ingestion into Archon Data Store. Chain of custody checks are run for each object, and their status is listed alongside. "
              + "Go through them to ensure your data has been mapped without errors.";
      report.addComponent(
          ComponentType.OBJECTIVE, ObjectiveBean.builder().description(reportDescription).build());

      Map<String, String> multipleCardValues = new LinkedHashMap<>();
      multipleCardValues.put("Ingestion Session Id", "1ef9b1d5-7533-4689-83fc");
      multipleCardValues.put("Scheduled By", "System");
      multipleCardValues.put("Scheduled Time", new Date().toString());
      multipleCardValues.put("Job Name", "Test Job");
      multipleCardValues.put("App Name", "Application");
      multipleCardValues.put("Schema Name", "Schema");
      multipleCardValues.put("Status", "Success");

      MultipleCardBean multipleCard =
          MultipleCardBean.builder()
                  .title("Table Details")
              .headerValue("ADS_DEMO_CHECK")
              .subHeaderValue("_003_METADATA_ADS.ADS_CONTENT_FS")
              .values(multipleCardValues)
              .build();
      report.addComponent(ComponentType.CARD_SECTION, multipleCard);

      report.addComponent(ComponentType.FOOTER, FooterBean.DEFAULT_CONFIG);
      report.render();
      report.close();
    } catch (FileNotFoundException e) {
      throw new IllegalArgumentException(e.getMessage());
    } catch (IOException e) {
      throw new IllegalArgumentException(e);
    }
  }
}
