package com.p3.ads.runner;

import com.p3.ads.core.Report;
import com.p3.ads.core.ReportBuilder;
import com.p3.ads.enums.ComponentType;
import com.p3.ads.enums.FontFamilyType;
import com.p3.ads.enums.TableType;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static runner.constants.CommonConstants.JOB_SUMMARY;

public class Runner {

    public static void main(String[] args) {

        try {
            String outputPath = "/home/p3/IdeaProjects/Report_Utility/output";
            Report report = new ReportBuilder(outputPath, "Report_Corrections.pdf").build();
            report.addComponent(ComponentType.HEADER, HeaderBean.DEFAULT_CONFIG);
            Map<String, String> parameters = new LinkedHashMap<>();
            parameters.put("Generated By", "Sysadmin");
            parameters.put("View Activity Session Id", "1234567890");
            parameters.put("Report Generated Time", new Date().toString());

            Map<String, String> jobSummaryParameters = new LinkedHashMap<>();
            jobSummaryParameters.put("Scheduled By", "Sysadmin");
            jobSummaryParameters.put("Scheduled Time", new Date().toString());
            jobSummaryParameters.put("Start Time", new Date().toString());
            jobSummaryParameters.put("End Time", new Date().toString());
            jobSummaryParameters.put("Total Time", new Date().toString());

            Map<String, String> additionalParameters = new LinkedHashMap<>();
            additionalParameters.put("Record Count Before Refresh", "0");
            additionalParameters.put("Record Count After Refresh", "702");

            TableBean tableBean = TableBean.builder()
                    .title("Optimization Statistics")
                    .headers(List.of("Description", "Count of pre-data optimization",
                            "Count of pre-data optimization", "Message"))
                    .values(List.of(
                            List.of("Data Snapshots", "2", "1", "1 snapshot removed"),
                            List.of("Data files", "8", "1", "8 files merged as 1"),
                            List.of("Size of Table", "85.432 KB", "23.745 KB", "Table size reduced to 23.745 KB")
                    ))
                    .headerFontFamily(FontFamilyType.ROBOTO_REGULAR)
                    .cellFontFamily(FontFamilyType.ROBOTO_REGULAR)
                    .headerFontSize(12)
                    .cellFontSize(10)
                    .build();

            report.addComponent(ComponentType.GRID_SECTION, GridTableBean.builder().gridValues(parameters).build());
            report.addComponent(ComponentType.GRID_SECTION, GridTableBean.builder().gridValues(jobSummaryParameters)
                    .title(JOB_SUMMARY)
                    .tableType(TableType.SUMMARY)
                    .isJobStatusInclusion(true)
                    .build());
            String reportDescription = "This report contains details of the end-to-end data and metadata track of the data object from the point of extraction to "
                    + "ingestion into Archon Data Store. Chain of custody checks are run for each object, and their status is listed alongside. "
                    + "Go through them to ensure your data has been mapped without errors.";
            report.addComponent(ComponentType.OBJECTIVE, ObjectiveBean.builder().description(reportDescription).build());

//            report.addComponent(ComponentType.GRID_SECTION, GridTableBean.builder()
//                    .gridValues(additionalParameters)
//                    .tableType(TableType.SUMMARY)
//                    .title("Additional Details").build());

            report.addComponent(ComponentType.TABLE, tableBean);
            report.addComponent(ComponentType.FOOTER, FooterBean.DEFAULT_CONFIG);

            report.addComponent(ComponentType.CHART_SECTION, ChartCreationConfig.DEFAULT_CONFIG);

            report.render();
            report.close();
        } catch (FileNotFoundException e) {
            throw new IllegalArgumentException(e.getMessage());
        } catch (IOException e) {
            throw new IllegalArgumentException(e);
        }


    }

}
